import type { ListingDetail } from "../_lib/listingDetail";

export const mockListings: Record<string, ListingDetail> = {
  "1": {
    id: "1",
    title: "Oakwood Adult Family Home",
    address: "123 Oak Street, Kirkland, WA 98033",
    careTypes: [
      { label: "Adult Family Home", color: "orange" },
      { label: "Assisted Living", color: "teal" },
    ],
    price: 3800,
    maxPrice: 4500,
    rating: 4.9,
    reviewCount: 34,
    bedsAvailable: 1,
    capacity: 6,
    staffRatio: "1:3",
    phone: "(425) 555-0100",
    email: "info@oakwoodafh.com",
    website: "www.oakwoodafh.com",
    licenseNumber: "AFH-123456",
    established: "2010",
    images: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
      "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&q=80",
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
    ],
    description:
      "Oakwood Adult Family Home provides personalized care in a warm, residential setting. Our intimate home environment offers individualized attention and a family-like atmosphere for residents.",
    careServices: [
      "Medication management",
      "Personal care assistance",
      "24-hour supervision",
      "Meal preparation",
    ],
    amenities: [
      "Private rooms",
      "Shared common areas",
      "Outdoor patio",
      "WiFi",
      "Housekeeping",
      "Laundry service",
    ],
    activities: [
      "Daily activities",
      "Social gatherings",
      "Outdoor walks",
      "Games and puzzles",
    ],
    diningOptions: [
      "Three meals daily",
      "Snacks available",
      "Special dietary accommodations",
    ],
    safetyFeatures: [
      "Emergency call system",
      "Fire safety",
      "Wheelchair accessible",
      "Secure entrance",
      "24-hour supervision",
    ],
    certifications: ["State licensed", "Medicaid certified"],
    insuranceAccepted: [
      "Medicaid",
      "Private insurance",
      "Long-term care insurance",
    ],
    treatmentServices: [],
  },
  "2": {
    id: "2",
    title: "Evergreen Memory Care",
    address: "456 Pine Street, Seattle, WA 98101",
    careTypes: [{ label: "Memory Care", color: "purple" }],
    price: 6500,
    maxPrice: 9500,
    rating: 4.8,
    reviewCount: 89,
    bedsAvailable: 2,
    capacity: 48,
    staffRatio: "1:5",
    phone: "(206) 555-0202",
    email: "info@evergreenmemorycare.com",
    website: "www.evergreenmemorycare.com",
    licenseNumber: "MC-1234567",
    established: "2012",
    images: [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
      "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&q=80",
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
    ],
    description:
      "Evergreen Memory Care specializes in providing compassionate care for individuals living with Alzheimer's and dementia. Our purpose-built community features secure neighborhoods, easy-to-navigate layouts, and calming environments designed to reduce anxiety and promote well-being.",
    descriptionExtra:
      "Our specialized staff receives ongoing training in evidence-based approaches to memory care, ensuring residents receive the highest quality of support.",
    careServices: [
      "Medication management",
      "Memory care",
      "24-hour nursing",
      "Vital monitoring",
    ],
    amenities: [
      "Private rooms",
      "Beauty salon",
      "Restaurant-style dining",
      "Laundry service",
      "Outdoor spaces",
      "WiFi",
      "Housekeeping",
    ],
    activities: [
      "Music therapy",
      "Gentle exercise",
      "Sensory activities",
      "Reminiscence therapy",
    ],
    diningOptions: [
      "Three meals daily",
      "Finger food options",
      "Special dietary accommodations",
    ],
    safetyFeatures: [
      "Emergency call system",
      "Fire safety",
      "Wheelchair accessible",
      "Wandering prevention",
      "Secure entrance",
      "Fall prevention",
      "24-hour security",
    ],
    certifications: [
      "State licensed",
      "Medicare certified",
      "Medicaid certified",
    ],
    insuranceAccepted: [
      "Medicare",
      "Medicaid",
      "Private insurance",
      "Long-term care insurance",
    ],
    treatmentServices: [],
  },
  "3": {
    id: "3",
    title: "Sunrise Senior Living at Bellevue",
    address: "123 Bellevue Way NE, Bellevue, WA 98004",
    careTypes: [
      { label: "Assisted Living", color: "teal" },
      { label: "Memory Care", color: "purple" },
    ],
    price: 4500,
    maxPrice: 8500,
    rating: 4.7,
    reviewCount: 127,
    bedsAvailable: 4,
    capacity: 85,
    staffRatio: "1:8",
    phone: "(425) 555-0101",
    email: "bellevue@sunriseseniorliving.com",
    website: "www.sunriseseniorliving.com",
    licenseNumber: "AL-0892341",
    established: "2005",
    images: [
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
    ],
    description:
      "Sunrise Senior Living at Bellevue provides compassionate, personalized care in a beautiful Pacific Northwest setting. Our community offers a warm, homelike environment where residents enjoy individualized care plans, engaging activities, and delicious chef-prepared meals. With a dedicated team available 24/7, families can have peace of mind knowing their loved ones are safe and cared for.",
    descriptionExtra:
      "Our memory care neighborhood, Reminiscence, provides specialized care for those living with Alzheimer's and other forms of dementia, with specially trained team members and purposeful programming.",
    careServices: [
      "Medication management",
      "Physical therapy",
      "24-hour nursing",
      "Memory care",
      "Vital monitoring",
    ],
    amenities: [
      "Private rooms",
      "Pet friendly",
      "Outdoor spaces",
      "Fitness center",
      "Beauty salon",
      "Library",
      "Chapel",
      "Transportation",
      "WiFi",
      "Restaurant-style dining",
      "Housekeeping",
      "Laundry service",
    ],
    activities: [
      "Arts & crafts",
      "Music therapy",
      "Exercise classes",
      "Social events",
      "Gardening",
      "Movie nights",
      "Outings",
    ],
    diningOptions: [
      "Three chef-prepared meals daily",
      "Special dietary accommodations",
      "All-day dining room",
      "Snacks and beverages",
    ],
    safetyFeatures: [
      "Emergency call system",
      "Secure entrance",
      "Fire safety",
      "Fall prevention",
      "Wheelchair accessible",
      "24-hour security",
    ],
    certifications: [
      "State licensed",
      "Medicare certified",
      "Joint Commission accredited",
    ],
    insuranceAccepted: [
      "Medicare",
      "Private insurance",
      "Long-term care insurance",
    ],
    treatmentServices: [],
  },
  "4": {
    id: "4",
    title: "Cascade Independent Living",
    address: "789 Cascade Drive, Redmond, WA 98052",
    careTypes: [{ label: "Independent Living", color: "blue" }],
    price: 2800,
    maxPrice: 4200,
    rating: 4.5,
    reviewCount: 78,
    bedsAvailable: 12,
    capacity: 120,
    staffRatio: "1:15",
    phone: "(425) 555-0102",
    email: "info@cascadeindependent.com",
    website: "www.cascadeindependent.com",
    licenseNumber: "IL-4567890",
    established: "2008",
    images: [
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
      "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&q=80",
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800&q=80",
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
    ],
    description:
      "Cascade Independent Living provides an active, maintenance-free lifestyle for seniors. Enjoy spacious apartments, resort-style amenities, and a vibrant social community while maintaining your independence.",
    careServices: [
      "Emergency response system",
      "Wellness programs",
      "Health screenings",
      "Medication reminders",
    ],
    amenities: [
      "Private apartments",
      "Fitness center",
      "Swimming pool",
      "Restaurant-style dining",
      "Library",
      "Game room",
      "Outdoor spaces",
      "WiFi",
      "Housekeeping",
      "Transportation",
    ],
    activities: [
      "Fitness classes",
      "Arts and crafts",
      "Book club",
      "Social events",
      "Day trips",
    ],
    diningOptions: [
      "Three meals daily",
      "Snacks available",
      "Special dietary accommodations",
    ],
    safetyFeatures: [
      "Emergency call system",
      "Fire safety",
      "Wheelchair accessible",
      "Secure entrance",
      "24-hour security",
    ],
    certifications: ["State licensed"],
    insuranceAccepted: ["Private insurance", "Long-term care insurance"],
    treatmentServices: [],
  },
};
